#!/command/with-contenv sh
set -e
. /etc/s6-overlay/scripts/env.sh
LD=$(ls /opt/edge-lib/*-linux-gnu/ld-linux-*.so.2 | head -n1)
exec "$LD" --library-path "$(dirname "$LD")" /opt/bin/edge-runtime start --main-service /opt/functions/main --port 9000 --ip 127.0.0.1
